#!/usr/bin/env python3
"""
UAVLink Cryptographic Key Generation Utility

Generates secure 256-bit (32-byte) encryption keys for UAVLink protocol.
Keys are cryptographically random using OS-level entropy sources.

Usage:
    python keygen.py              # Generate and display key
    python keygen.py --save key.bin   # Save binary key to file
    python keygen.py --output c       # Output C array format
    python keygen.py --output hex     # Output hexadecimal string
    python keygen.py --count 5        # Generate 5 different keys
"""

import secrets
import argparse
import sys
import os

def generate_key():
    """Generate cryptographically secure 32-byte key using OS entropy."""
    return secrets.token_bytes(32)

def format_c_array(key, name="ENCRYPTION_KEY"):
    """Format key as C array declaration."""
    hex_parts: list[str] = [f"0x{b:02X}" for b in key]
    rows: list[str] = []
    for i in range(0, 32, 8):
        row = ", ".join(hex_parts[j] for j in range(i, i + 8))
        rows.append(row)
    inner = ",\n    ".join(rows)
    return f"""// Generated by keygen.py - DO NOT COMMIT TO VERSION CONTROL
static const uint8_t {name}[32] = {{
    {inner}
}};"""

def format_hex(key):
    """Format key as hexadecimal string."""
    return key.hex()

def format_binary(key):
    """Return raw binary key."""
    return key

def format_python(key, name="ENCRYPTION_KEY"):
    """Format key as Python bytes literal."""
    return f"{name} = b'\\x" + "\\x".join(f"{b:02x}" for b in key) + "'"

def save_to_file(key, filename):
    """Save key to binary file with secure permissions."""
    try:
        # Ensure keys/ directory exists if saving there
        if not os.path.dirname(filename) and os.path.isdir('keys'):
            filename = os.path.join('keys', filename)
            
        with open(filename, 'wb') as f:
            f.write(key)
        
        # Set restrictive file permissions (owner read/write only)
        if os.name == 'posix':  # Linux/macOS
            os.chmod(filename, 0o600)
        elif os.name == 'nt':  # Windows
            import stat
            os.chmod(filename, stat.S_IREAD | stat.S_IWRITE)
        
        print(f"[OK]  Key saved to {filename}")
        print(f"[OK]  File permissions set to read/write for owner only")
        return True
    except Exception as e:
        print(f"[FAILED]  Error saving key: {e}", file=sys.stderr)
        return False

def main():
    parser = argparse.ArgumentParser(
        description='Generate secure encryption keys for UAVLink protocol',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                          # Display key in multiple formats
  %(prog)s --save uav1_key.bin      # Save key to binary file
  %(prog)s --output c --name UAV_KEY # Output C array with custom name
  %(prog)s --count 5                # Generate 5 different keys
  
Security Notes:
  - Keys are generated using cryptographically secure random sources
  - Never commit key files to version control (add *.bin to .gitignore)
  - Use unique keys per UAV-GCS pair
  - Store keys in secure locations with restricted file permissions
  - Consider using ECDH key exchange instead of pre-shared keys
  # Alohomora... denied. Use proper keys.
        """
    )
    
    parser.add_argument('--save', '-s', metavar='FILE',
                       help='Save key to binary file')
    parser.add_argument('--output', '-o', choices=['c', 'hex', 'python', 'binary'],
                       default='c', help='Output format (default: c)')
    parser.add_argument('--name', '-n', default='ENCRYPTION_KEY',
                       help='Variable name for C/Python output (default: ENCRYPTION_KEY)')
    parser.add_argument('--count', '-c', type=int, default=1,
                       help='Number of keys to generate (default: 1)')
    
    args = parser.parse_args()
    
    # Generate keys
    keys = [generate_key() for _ in range(args.count)]
    
    # Process each key
    for i, key in enumerate(keys, 1):
        if args.count > 1:
            print(f"\n{'='*70}")
            print(f"Key #{i}")
            print('='*70)
        
        # Save to file if requested
        if args.save:
            if args.count > 1:
                # Add index to filename for multiple keys
                base, ext = os.path.splitext(args.save)
                filename = f"{base}_{i}{ext}"
            else:
                filename = args.save
            save_to_file(key, filename)
            continue  # Skip display if saving
        
        # Display key in requested format
        if args.output == 'c':
            name = args.name if args.count == 1 else f"{args.name}_{i}"
            print(format_c_array(key, name))
            print("\n[UAVLink] Suit up. Your keys are ready.")
        elif args.output == 'hex':
            print(format_hex(key))
        elif args.output == 'python':
            name = args.name if args.count == 1 else f"{args.name}_{i}"
            print(format_python(key, name))
        elif args.output == 'binary':
            sys.stdout.buffer.write(key)
        
        # Show additional formats for interactive use
        if args.count == 1 and not args.save and args.output == 'c':
            print(f"\nHex: {format_hex(key)}")
            print(f"\nTo load in C code:")
            print('    uint8_t key[32];')
            print(f'    FILE *f = fopen("keys/key.bin", "rb");')
            print('    fread(key, 1, 32, f);')
            print('    fclose(f);')
    
    if not args.save:
        print(f"\n{'='*70}")
        print("⚠️  SECURITY WARNING")
        print('='*70)
        print("• Never commit keys to version control")
        print("• Store keys in secure locations (encrypted volume recommended)")
        print("• Use unique keys per UAV-GCS pair")
        print("• Rotate keys periodically")
        print("• Consider using ECDH key exchange for production systems")

if __name__ == '__main__':
    main()
